"""Evaluate square-function proposals with explicit, typed candidate rejections.

Run from the OpenEvolve repository root with the command in README.md. The
evaluator returns ``CandidateRejected`` for candidate defects and numeric
metrics for valid candidates. It does not turn infrastructure errors into
candidate rejections.
"""

from __future__ import annotations

import ast
import importlib.util
import math
from pathlib import Path

from openevolve.rejection import CandidateRejected, reject_candidate


def evaluate(program_path: str) -> dict[str, float] | CandidateRejected:
    """Score an implementation of ``square`` or reject a broken candidate.

    Args:
        program_path: Path to a Python candidate generated by OpenEvolve.

    Returns:
        A score between zero and one for a callable, finite implementation, or
        a typed rejection for syntax, interface, or candidate runtime defects.
    """
    path = Path(program_path)
    source = path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source, filename=str(path))
    except SyntaxError as exc:
        return reject_candidate(
            category="static_invalid",
            code="python_syntax_error",
            rationale="The proposed Python program does not parse.",
            evidence={"exception_type": "SyntaxError", "line": exc.lineno},
            repairable=True,
        )

    # Check the required interface before loading the candidate module.
    if not any(isinstance(node, ast.FunctionDef) and node.name == "square" for node in tree.body):
        return reject_candidate(
            category="static_invalid",
            code="square_function_missing",
            rationale="The candidate must define a top-level square(value) function.",
            evidence={"validator_code": "required_function", "stage": "static_check"},
            repairable=True,
        )

    spec = importlib.util.spec_from_file_location("typed_rejection_candidate", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Cannot load candidate module from {path}")
    module = importlib.util.module_from_spec(spec)
    try:
        spec.loader.exec_module(module)
        square = module.square
        if not callable(square):
            raise TypeError("square is not callable")
        # Use several inputs so the initial estimate has a nonzero score and
        # evolution can improve it without requiring any extra dependencies.
        errors = []
        for value in (-2.0, -1.0, 0.0, 1.0, 2.0):
            result = square(value)
            if isinstance(result, bool) or not isinstance(result, (int, float)):
                raise TypeError("square must return a real number")
            if not math.isfinite(result):
                raise ValueError("square must return a finite number")
            errors.append(abs(result - value * value))
    except Exception as exc:
        return reject_candidate(
            category="runtime_candidate_failure",
            code="square_execution_failed",
            rationale=f"The candidate failed while running square: {type(exc).__name__}.",
            evidence={"exception_type": type(exc).__name__, "stage": "evaluation"},
            repairable=True,
        )

    mean_error = sum(errors) / len(errors)
    return {"combined_score": 1.0 / (1.0 + mean_error), "mean_absolute_error": mean_error}
